# GCC support can be specified at major, minor, or micro version
# (e.g. 8, 8.2 or 8.2.0).
# See https://hub.docker.com/r/library/gcc/ for all supported GCC
# tags from Docker Hub.
# See https://docs.docker.com/samples/library/gcc/ for more on how to use this image
# FROM gcc:latest

# # These commands copy your files into the specified directory in the image
# # and set that as the working location
# COPY . /usr/src/myapp
# ADD /data /usr/src/myapp/data
# WORKDIR /usr/src/myapp

# # This command compiles your app using GCC, adjust for your source code
# RUN gcc main.c thpool.c -D THPOOL_DEBUG -pthread -o main

# # This command runs your application, comment out this line to compile only
# CMD [ "./main"]

# LABEL Name=proyecto2 Version=0.0.1


FROM python:3.8-slim-buster

COPY . /usr/src/myapp
ADD /data /usr/src/myapp/data
WORKDIR /usr/src/myapp

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

CMD ["python3", "main.py"]